### ISSUE TITLE
updating/restarting container clears configuration

### ISSUE THREAD

**Issue by erikbelusic** [linuxserver/docker-davos#10]
I am using unRAID server Pro, version 6.6.7.

I am using the default template settings, with the exception of the download directory pointing to my own specified location

when updating or restarting my container, configuration is lost. I have removed and reconfigured the container. after creating a host, no db file is added to the config directory like it used to be. The log file is also no longer making it into that directory where it should be saved

**Comment by thelamer** [comment]
@erikbelusic this was 100% my fault. 

Please update to the latest image this is now fixed, the build env I setup for the new image did not include a flag required to build a production Jar for this app. So it was stuck running in a debug mode.
